### PR TITLE
Change font and Updated UI look

### PR DESCRIPTION
**Pull request by danish-faisal**
Replaced Metropolis font with Montserrat font
And designed images in Home page

### CODE REVIEW

**Comment by danish-faisal** [comment]
Before
Before

After Changes
After-Changes

**Comment by LoopThrough-i-j** [comment]
@danish-faisal everything looks good to me for merge. I would also like to see how this looks with the font [Sen](https://fonts.google.com/specimen/Sen).

**Comment by LoopThrough-i-j** [comment]
@danish-faisal also could you work and fix the `auto-comment` action with some other GitHub action available in the marketplace for commenting on issues and PRs.

**Comment by danish-faisal** [comment]
@LoopThrough-i-j I couldn't find an alternative of  auto-comment with all it's functionalities

I see that you've made some changes for the fix
shall I merge them and create a new PR?

**Comment by LoopThrough-i-j** [comment]
@danish-faisal thanks for working on this. Merged the PR. 
As I couldn't get a lot of time to work on the issue. Would like to see one more PR fixing the commenter if possible.

**Pull request merged**
