### PR TITLE
uploaded thumbnail for bubble sort in images folder under assets

### PR DESCRIPTION
**Pull request by aumdavda**
Made a thumbnail for bubble sort and uploaded it in assests/images/thumbnails.Hope you like it

### CODE REVIEW

**Comment by LoopThrough-i-j** [comment]
The image doesn't say bubble sort!!

**Comment by aumdavda** [comment]
@LoopThrough-i-j please explain what i should add?

**Comment by aumdavda** [comment]
it says in the title so do you mean bubble sort illustratively?

**Comment by aumdavda** [comment]
Teens and Teens Sorting Math Worksheet (1280 x 720 px) (1)
@LoopThrough-i-j I put the sorting in the pc screen, please accept the request

**Comment by LoopThrough-i-j** [comment]
@Ruchip16 would you guide, on what he should make.

**Comment by aumdavda** [comment]
I attached a photo,please see it

**Comment by Ruchip16** [comment]
@aumdavda plz attach a ss of what you have made here I am unable to see it

**Comment by aumdavda** [comment]
@ruchi here you go
should I make a pull request with this new/final thumbnail?

**Comment by Ruchip16** [comment]
@aumdavda plz dont reply in the mail it creates spam and also the screenshot is not visible there upload the ss here

**Pull request closed without merging**
