### PR TITLE
I Desgined the thumbnail for Getting Started with API

### PR DESCRIPTION
**Pull request by anmolsingh0219**
I have Added a new thumbnail for Getting Started with API in Assets>images>thumbnails

### CODE REVIEW

**Comment by LoopThrough-i-j** [comment]
Looks good to me but where is the blog?

**Comment by anmolsingh0219** [comment]
> Looks good to me but where is the blog?

As far as I know, we were only asked to design the thumbnail for the given topics
Correct me if I am wrong

**Comment by anmolsingh0219** [comment]
> Looks good to me but where is the blog?

I have made this in 

> Looks good to me but where is the blog?

I have made this following the issue design thumbnails for blogsp

> Looks good to me but where is the blog?

I made this following the issue "Design thumbnails for blogpost"

**Comment by LoopThrough-i-j** [comment]
Then please consider creating thumbs for the categories as well, in this PR.

**Comment by anmolsingh0219** [comment]
> Then please consider creating thumbs for the categories as well, in this PR.

Sure

**Comment by anmolsingh0219** [comment]
How does API work

Here's One more thumbnail on How Does API work! @LoopThrough-i-j @niyoj @Ruchip16

**Comment by LoopThrough-i-j** [comment]
@Ruchip16 feel free to merge if it looks good.

**Comment by Ruchip16** [comment]
> @Ruchip16 feel free to merge if it looks good.

cool

**Comment by anmolsingh0219** [comment]
A cross is shown in front of my merged pull request, what should I do please guide me @LoopThrough-i-j

**Pull request merged**
