### PR TITLE
Changed Backend Image

### PR DESCRIPTION
**Pull request by ashusengar**
Changed Backend Image as in the previous image an **external link** was visible. the current image gives more impact and looks good with the UI of the website.

### CODE REVIEW

**Comment by LoopThrough-i-j** [comment]
Can you share some screenshots of how it will look?

**Comment by LoopThrough-i-j** [comment]
@ashusengar would you mind changing other images as well, other than leetcode?

**Comment by ashusengar** [comment]
@LoopThrough-i-j Sure, I will create a separate PR according to the pages and will try to create a smooth UI.

**Comment by ashusengar** [comment]
@LoopThrough-i-j Sure, I will change the Image for the Frontend section and DSA section.

**Comment by ashusengar** [comment]
@Ruchip16 @LoopThrough-i-j I have changed the Images, Please review it

**Pull request merged**
