### PR TITLE
Added new responsive hamburger menu in the homepage

### PR DESCRIPTION
**Pull request by Neenu-12**
Created a new navigation bar for the home page , for shorter screen sizes added a responsive hamburger menu.

### CODE REVIEW

**Comment by LoopThrough-i-j** [comment]
@Neenu-12 could you please put 1 or 2 screenshots for a few screen sizes?

**Comment by Neenu-12** [comment]
@LoopThrough-i-j  here are some screenshots
Screen_greater_than_980px
Screen_less_than_980px_1
Screen_less_than_980px_2

**Comment by LoopThrough-i-j** [comment]
@Neenu-12 LGTM. Thanks for your contribution.

**Comment by Neenu-12** [comment]
> @Neenu-12 LGTM. Thanks for your contribution.

@LoopThrough-i-j  My pleasure

**Pull request merged**
