### PR TITLE
added auto-commenter

### LINKED ISSUE #15: Adding Auto Commentor on Issues and PR's
I'll take this!

### PR DESCRIPTION
**Pull request by AnirudhPanda**
Added auto commenter for ISSUES and PULL REQUEST [Tested too](https://github.com/AnirudhPanda/Mentro-Community-Blog/pull/1#issuecomment-931941858) @Ruchip16 

Fixes #15

### CODE REVIEW

**Comment by LoopThrough-i-j** [comment]
Thanks a lot, @AnirudhPanda  for the contribution, would you mind adding links to how to contribute and the guidelines, and ask people to make sure they have followed those, before asking for a final review.

I will close and merge the PR once ready, thanks for the great work.

**Comment by AnirudhPanda** [comment]
> Thanks a lot, @AnirudhPanda for the contribution, would you mind adding links to how to contribute and the guidelines, and ask people to make sure they have followed those, before asking for a final review. Asking people about mentioning the issue they have raised PR for, will also be very important, to make sure we can close the issue once the PR is merged and no one else is working on the same issue.
> 
> I will close and merge the PR once ready, thanks for the great work.

Can you give me what to add exactly?

And adding too much information may look boring and most people would not read it completely!!

Talking from a user perspective! @LoopThrough-i-j

**Comment by LoopThrough-i-j** [comment]
> > Thanks a lot, @AnirudhPanda for the contribution, would you mind adding links to how to contribute and the guidelines, and ask people to make sure they have followed those, before asking for a final review. Asking people about mentioning the issue they have raised PR for, will also be very important, to make sure we can close the issue once the PR is merged and no one else is working on the same issue.
> > I will close and merge the PR once ready, thanks for the great work.
> 
> Can you give me what to add exactly?
> 
> And adding too much information may look boring and most people would not read it completely!!
> 
> Talking from a user perspective! @LoopThrough-i-j

The things I mentioned should be on PRs to make sure it's easy to communicate and an instant check from both sides.

The things to mention more are.
```
Before asking for a review make sure to:
-  Go through the [contribution guidelines](https://github.com/Mentro-Org/Mentro-Community-Blog/blob/main/contributing.md)
- Mention the issue for which the PR is raised to track the progress of the issue. In case an issue is not created, please create an issue for the PR.
```

**Comment by AnirudhPanda** [comment]
> > > Thanks a lot, @AnirudhPanda for the contribution, would you mind adding links to how to contribute and the guidelines, and ask people to make sure they have followed those, before asking for a final review. Asking people about mentioning the issue they have raised PR for, will also be very important, to make sure we can close the issue once the PR is merged and no one else is working on the same issue.
> > > I will close and merge the PR once ready, thanks for the great work.
> > 
> > 
> > Can you give me what to add exactly?
> > And adding too much information may look boring and most people would not read it completely!!
> > Talking from a user perspective! @LoopThrough-i-j
> 
> The things I mentioned should be on PRs to make sure it's easy to communicate and an instant check from both sides.
> 
> The things to mention more are.
> 
> ```
> Before asking for a review make sure to:
> -  Go through the [contribution guidelines](https://github.com/Mentro-Org/Mentro-Community-Blog/blob/main/contributing.md)
> - Mention the issue for which the PR is raised to track the progress of the issue. In case an issue is not created, please create an issue for the PR.
> ```

Did the changes @LoopThrough-i-j

**Comment by LoopThrough-i-j** [comment]
Great work, thanks @AnirudhPanda.

**Pull request merged**
